networks:
  game_network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - game_network

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    depends_on:
      mongo:
        condition: service_started
    ports:
      - "${CORE_PORT}:8080"
    networks:
      - game_network
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=mongo:27017
      - MONGO_NETWORK=threefortengame_game_network
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}

  aiplayer:
    build:
      context: .
      dockerfile: aiplayer/Dockerfile
    depends_on:
      mongo:
        condition: service_started
      core:
        condition: service_started
    ports:
      - "${AIPLAYER_PORT}:8080"
    networks:
      - game_network
    environment:
      - CORE_HOST=core:8080